// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-EtHvgb14c5UzVggOoJRa6j8oto53Jg',
    appId: '1:725835190067:android:1a8871c3f15cdafae53846',
    messagingSenderId: '725835190067',
    projectId: 'elevate-flower-app',
    storageBucket: 'elevate-flower-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABD3fIZrCMoxFhtNpvSRhY9ZHTHt49rQU',
    appId: '1:725835190067:ios:3af9533994ff8587e53846',
    messagingSenderId: '725835190067',
    projectId: 'elevate-flower-app',
    storageBucket: 'elevate-flower-app.firebasestorage.app',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKWdkFjeKkEAfKFrMO2svs48t2d9OqRGw',
    appId: '1:725835190067:web:86225b1572d53a90e53846',
    messagingSenderId: '725835190067',
    projectId: 'elevate-flower-app',
    authDomain: 'elevate-flower-app.firebaseapp.com',
    storageBucket: 'elevate-flower-app.firebasestorage.app',
  );
}
